### ISSUE TITLE
activate subproject

### ISSUE THREAD

**Issue by nsheff** [databio/projectInit#18]
projectInit needs to pass subprojects to pepr.

**Comment by stolarczyk** [comment]
should we add another parameter (subproject name to be activated) to the `projectInit` function interface? 

`subproject`?

**Comment by nsheff** [comment]
yeah, I think you're probably right. does it already do this on `dev`?

**Comment by stolarczyk** [comment]
In `projectInit`? No. I can work on it, though. Should be easy to add
