### ISSUE TITLE
dirOut function errors in dev

### ISSUE THREAD

**Issue by stolarczyk** [databio/projectInit#20]
```
> dirOut()
Error in dirWrap("ROUT.DIR", ...) : could not find function "dirWrap"
```

The `dirWrap` function was deleted in `dev` in fcb6afb5aa2cfc2d90153d733746fcde427fe495

**Comment by nsheff** [comment]
I think this may reflect #21

**Comment by nsheff** [comment]
dirWrap  (and indeed all the dir functions) are now deprecated.
