### ISSUE TITLE
Add Imports (or maybe Depends ?) on folderfun

### ISSUE THREAD

**Issue by vreuter** [databio/projectInit#23]
Right now, issues installation issues perhaps from multiple `libcurl` instances on Rivanna are blocking this, as adding the needed statements to `DESCRIPTION` prevents installation with `install_local` or `install_github`, something like:
```
> install_github("databio/projectInit")
Error in curl::new_handle() : An unknown option was passed in to libcurl
```
But we should add this once the `libcurl ` woes resolve. Related to #21

**Comment by nsheff** [comment]
this is a rivanna configuration issue. you have to unload anaconda to install R packages.

Anyway, I've added the `folderfun` dependency
